[phases.install]
cmds = ["python -m pip install -r django_front/requirements.txt"]

[phases.build]
cmds = ["cd django_front && python manage.py collectstatic --noinput"]

[start]
cmd = "cd django_front && gunicorn django_front.wsgi --bind 0.0.0.0:${PORT:-8000}"

